openapi: 3.1.0
info:
  title: Ikigai API
  version: 2.0.0
  description: |
    # 🎓 Ikigai Learning Platform API
    
    Документация для API платформы онлайн обучения Ikigai.
    
    ## 📋 Основные возможности
    - 🔐 Аутентификация и управление пользователями
    - 📚 Управление курсами и уроками
    - 💳 Система платежей и транзакций
    - 📊 Административная панель

# servers:
#   - url: https://api.ikigai.com/v2
#     description: "🟢 Production API v2"
#   - url: https://staging-api.ikigai.com/v2
#     description: "🟡 Staging API v2"
#   - url: https://dev-api.ikigai.com/v2
#     description: "🔵 Development API v2"

# components:
#   securitySchemes:
#     BearerAuth:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
#       description: |
#         JWT токен, полученный при авторизации через `/auth/login`.
        
#         **Формат заголовка**: `Authorization: Bearer <token>`
        
#         **Время жизни**: 24 часа  
#         **Обновление**: используйте `/auth/refresh`

security:
  - BearerAuth: []

tags:
  - name: auth
    description: "🔐 Аутентификация и авторизация"
  
  - name: public
    description: "🎓 API для студентов"
  
  - name: admin
    description: "⚙️ Административный API"

paths:
  # Маршруты для авторизации
  /auth/login:
    post:
      summary: "Вход в систему"
      description: |
        Аутентификация пользователя по email и паролю.
        Возвращает JWT токен для дальнейших запросов.
      tags:
        - auth
      security: []  # Эндпоинт не требует авторизации
      $ref: ./auth/endpoints/auth.yaml#/Login
  
  /auth/register:
    post:
      summary: "Регистрация в системе"
      description: |
        Создание нового аккаунта пользователя.
        После регистрации отправляется письмо для подтверждения email.
      tags:
        - auth
      security: []  # Эндпоинт не требует авторизации
      $ref: ./auth/endpoints/auth.yaml#/Register

  /auth/register/confirm:
    post:
      summary: "Подтверждение регистрации"
      description: |
        Подтверждение email пользователя.
      tags:
        - auth 
      $ref: ./auth/endpoints/auth.yaml#/RegisterConfirm

  /auth/recover-password:
    post:
      summary: "Восстановление пароля"
      description: |
        Отправка письма для восстановления пароля.
      tags:
        - auth
      $ref: ./auth/endpoints/auth.yaml#/RecoverPassword

  /auth/recover-password/confirm:
    post:
      summary: "Подтверждение восстановления пароля"
      description: |
        Подтверждение кода из письма для восстановления пароля.
      tags:
        - auth
      $ref: ./auth/endpoints/auth.yaml#/ConfirmRecoverPassword
  
  /auth/logout:
    post:
      summary: "Выход из системы"
      description: |
        Инвалидация текущего JWT токена.
        После logout токен становится недействительным.
      tags:
        - auth
      $ref: ./auth/endpoints/auth.yaml#/Logout
  
  /auth/refresh:
    post:
      summary: "Обновление токена"
      description: |
        Получение нового JWT токена при помощи refresh token.
        Используется для продления сессии без повторного ввода пароля.
      tags:
        - auth
      $ref: ./auth/endpoints/auth.yaml#/Refresh

  # Публичные маршруты
  /courses/store:
    get:
      summary: "Получить каталог курсов"
      description: |
        Возвращает список всех доступных для покупки курсов.
      tags:
        - public
      $ref: ./edu/endpoints/courses.yaml#/getShopCourses
  
  /courses/my-courses:
    get:
      summary: "Мои приобретенные курсы"
      description: |
        Список курсов, которые купил авторизованный пользователь.
        Показывает прогресс изучения и последние активности.
      tags:
        - public
      $ref: ./edu/endpoints/courses.yaml#/getMyCourses
  
  /courses/{courseId}:
    get:
      summary: "Детальная информация о курсе"
      description: |
        Полная информация о курсе включая описание, программу обучения,
        отзывы и прогресс пользователя (если курс приобретен).
      tags:
        - public
      $ref: ./edu/endpoints/courses.yaml#/getCourse
  
  /courses/{courseId}/lessons:
    get:
      summary: "Список уроков курса"
      description: |
        Получить структуру курса с модулями и уроками.
        Доступ к контенту зависит от статуса покупки курса.
      tags:
        - public  
      $ref: ./edu/endpoints/courses.yaml#/getCourseLessons
  
  /lessons/{lessonId}:
    get:
      summary: "Содержимое урока"
      description: |
        Получить полное содержимое урока: видео, текст, задания.
        Доступно только для приобретенных курсов.
      tags:
        - public
      $ref: ./edu/endpoints/lessons.yaml#/getLesson
  
  /lessons/{lessonId}/complete:
    post:
      summary: "Отметить урок как завершенный"
      description: |
        Фиксация прохождения урока пользователем.
        Обновляет общий прогресс по курсу и может разблокировать следующие уроки.
      tags:
        - public
      $ref: ./edu/endpoints/lessons.yaml#/completeLesson
  
  /transactions:
    get:
      summary: "История транзакций"
      description: |
        Список всех платежных операций пользователя:
        покупки курсов, возвраты, подписки.
      tags:
        - public
      $ref: ./edu/endpoints/transactions.yaml#/getTransactions
  
  /users/me:
    get:
      summary: "Профиль пользователя"
      description: |
        Информация о текущем авторизованном пользователе:
        персональные данные, статистика обучения, настройки.
      tags:
        - public
      $ref: ./edu/endpoints/users.yaml#/getMe

  # Админ маршруты
  /admin/courses:
    get:
      summary: "Административный список курсов"
      description: |
        Получить все курсы в системе с расширенной информацией
        для администрирования: статистика, финансы, модерация.
      tags:
        - admin
      $ref: ./admin/endpoints/courses.yaml#/getAdminCourses
    post:
      summary: "Создать новый курс"
      description: |
        Создание курса в системе с базовой информацией.
        После создания можно добавлять модули и уроки.
      tags:
        - admin
      $ref: ./admin/endpoints/courses.yaml#/createAdminCourse

  /admin/courses/{courseId}:
    get:
      summary: "Детали курса для администратора"
      description: |
        Полная административная информация о курсе:
        статистика продаж, аналитика, настройки доступа.
      tags:
        - admin
      $ref: ./admin/endpoints/courses.yaml#/getAdminCourse
    patch:
      summary: "Обновить информацию о курсе"
      description: |
        Изменение метаданных курса: название, описание,
        цена, статус публикации, настройки доступа.
      tags:
        - admin
      $ref: ./admin/endpoints/courses.yaml#/updateAdminCourse
    delete:
      summary: "Удалить курс"
      description: |
        ⚠️ **Необратимая операция!**
        Полное удаление курса со всем контентом и статистикой.
      tags:
        - admin
      $ref: ./admin/endpoints/courses.yaml#/deleteAdminCourse

  /admin/courses/{courseId}/modules:
    get:
      summary: "Модули курса"
      description: |
        Структура курса: список всех модулей с уроками
        и настройками доступа для администрирования.
      tags:
        - admin
      $ref: ./admin/endpoints/modules.yaml#/getAdminCourseModules
    post:
      summary: "Создать модуль"
      description: |
        Добавление нового тематического модуля в курс.
        Модули группируют связанные по теме уроки.
      tags:
        - admin
      $ref: ./admin/endpoints/modules.yaml#/createAdminModule

  /admin/courses/{courseId}/modules/reorder:
    put:
      summary: "Изменить порядок модулей"
      description: |
        Переупорядочивание модулей в курсе.
        Влияет на последовательность изучения для студентов.
      tags:
        - admin
      $ref: ./admin/endpoints/modules.yaml#/reorderAdminModules

  /admin/modules/{moduleId}:
    get:
      summary: "Получить основную информацию о модуле"
      tags:
        - admin
      $ref: ./admin/endpoints/modules.yaml#/getAdminModule
    patch:
      summary: "Обновить основную информацию о модуле"
      tags:
        - admin
      $ref: ./admin/endpoints/modules.yaml#/updateAdminModule
    delete:
      summary: "Удалить модуль по id"
      tags:
        - admin
      $ref: ./admin/endpoints/modules.yaml#/deleteAdminModule
    
  /admin/modules/{moduleId}/lessons:
    get:
      summary: "Получить список уроков модуля"
      tags:
        - admin
      $ref: ./admin/endpoints/modules.yaml#/getAdminModuleLessons
    post:
      summary: "Создать урок"
      tags:
        - admin
      $ref: ./admin/endpoints/modules.yaml#/createAdminModuleLesson

  /admin/modules/{moduleId}/lessons/reorder:
    put:
      summary: "Изменить порядок уроков в модуле"
      description: |
        Переупорядочивание уроков внутри модуля.
        Определяет логическую последовательность обучения.
      tags:
        - admin
      $ref: ./admin/endpoints/lessons.yaml#/reorderAdminLessons
    
  /admin/lessons/{lessonId}:
    get:
      summary: "Содержимое урока для администратора"
      description: |
        Получить полное содержимое урока: видео, текст, задания.
        Административная версия с дополнительными возможностями редактирования.
      tags:
        - admin
      $ref: ./admin/endpoints/lessons.yaml#/getAdminLesson
    patch:
      summary: "Обновить содержимое урока"
      description: |
        Изменение контента урока: видео, текст, задания, настройки доступа.
        Полное редактирование всех элементов урока.
      tags:
        - admin
      $ref: ./admin/endpoints/lessons.yaml#/updateAdminLesson
    delete:
      summary: "Удалить урок по id"
      description: |
        ⚠️ **Необратимая операция!**
        Полное удаление урока со всем контентом.
      tags: 
        - admin
      $ref: ./admin/endpoints/lessons.yaml#/deleteAdminLesson

  /admin/users:
    get:
      summary: "Получить список пользователей"
      tags:
        - admin
      $ref: ./admin/endpoints/users.yaml#/getAdminUsers

  /admin/transactions:
    get:
      summary: "Получить список транзакций"
      tags:
        - admin
      $ref: ./admin/endpoints/transactions.yaml#/getAdminTransactions
