/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as AuthGuardImport } from './routes/auth/_guard';
import { Route as AdminGuardImport } from './routes/admin/_guard';
import { Route as educationGuardImport } from './routes/(education)/_guard';
import { Route as educationGuardIndexImport } from './routes/(education)/_guard/index';
import { Route as AuthGuardSignUpImport } from './routes/auth/_guard/sign-up';
import { Route as AuthGuardSignInImport } from './routes/auth/_guard/sign-in';
import { Route as AuthGuardRecoverPasswordImport } from './routes/auth/_guard/recover-password';
import { Route as AdminGuardDashboardImport } from './routes/admin/_guard/dashboard';
import { Route as educationGuardTestImport } from './routes/(education)/_guard/test';

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')();
const AdminImport = createFileRoute('/admin')();
const educationImport = createFileRoute('/(education)')();

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any);

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any);

const educationRoute = educationImport.update({
  id: '/(education)',
  getParentRoute: () => rootRoute,
} as any);

const AuthGuardRoute = AuthGuardImport.update({
  id: '/_guard',
  getParentRoute: () => AuthRoute,
} as any);

const AdminGuardRoute = AdminGuardImport.update({
  id: '/_guard',
  getParentRoute: () => AdminRoute,
} as any);

const educationGuardRoute = educationGuardImport.update({
  id: '/_guard',
  getParentRoute: () => educationRoute,
} as any);

const educationGuardIndexRoute = educationGuardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => educationGuardRoute,
} as any);

const AuthGuardSignUpRoute = AuthGuardSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthGuardRoute,
} as any);

const AuthGuardSignInRoute = AuthGuardSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthGuardRoute,
} as any);

const AuthGuardRecoverPasswordRoute = AuthGuardRecoverPasswordImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => AuthGuardRoute,
} as any);

const AdminGuardDashboardRoute = AdminGuardDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminGuardRoute,
} as any);

const educationGuardTestRoute = educationGuardTestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => educationGuardRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(education)': {
      id: '/(education)';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof educationImport;
      parentRoute: typeof rootRoute;
    };
    '/(education)/_guard': {
      id: '/(education)/_guard';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof educationGuardImport;
      parentRoute: typeof educationRoute;
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminImport;
      parentRoute: typeof rootRoute;
    };
    '/admin/_guard': {
      id: '/admin/_guard';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminGuardImport;
      parentRoute: typeof AdminRoute;
    };
    '/auth': {
      id: '/auth';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    '/auth/_guard': {
      id: '/auth/_guard';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof AuthGuardImport;
      parentRoute: typeof AuthRoute;
    };
    '/(education)/_guard/test': {
      id: '/(education)/_guard/test';
      path: '/test';
      fullPath: '/test';
      preLoaderRoute: typeof educationGuardTestImport;
      parentRoute: typeof educationGuardImport;
    };
    '/admin/_guard/dashboard': {
      id: '/admin/_guard/dashboard';
      path: '/dashboard';
      fullPath: '/admin/dashboard';
      preLoaderRoute: typeof AdminGuardDashboardImport;
      parentRoute: typeof AdminGuardImport;
    };
    '/auth/_guard/recover-password': {
      id: '/auth/_guard/recover-password';
      path: '/recover-password';
      fullPath: '/auth/recover-password';
      preLoaderRoute: typeof AuthGuardRecoverPasswordImport;
      parentRoute: typeof AuthGuardImport;
    };
    '/auth/_guard/sign-in': {
      id: '/auth/_guard/sign-in';
      path: '/sign-in';
      fullPath: '/auth/sign-in';
      preLoaderRoute: typeof AuthGuardSignInImport;
      parentRoute: typeof AuthGuardImport;
    };
    '/auth/_guard/sign-up': {
      id: '/auth/_guard/sign-up';
      path: '/sign-up';
      fullPath: '/auth/sign-up';
      preLoaderRoute: typeof AuthGuardSignUpImport;
      parentRoute: typeof AuthGuardImport;
    };
    '/(education)/_guard/': {
      id: '/(education)/_guard/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof educationGuardIndexImport;
      parentRoute: typeof educationGuardImport;
    };
  }
}

// Create and export the route tree

interface educationGuardRouteChildren {
  educationGuardTestRoute: typeof educationGuardTestRoute;
  educationGuardIndexRoute: typeof educationGuardIndexRoute;
}

const educationGuardRouteChildren: educationGuardRouteChildren = {
  educationGuardTestRoute: educationGuardTestRoute,
  educationGuardIndexRoute: educationGuardIndexRoute,
};

const educationGuardRouteWithChildren = educationGuardRoute._addFileChildren(educationGuardRouteChildren);

interface educationRouteChildren {
  educationGuardRoute: typeof educationGuardRouteWithChildren;
}

const educationRouteChildren: educationRouteChildren = {
  educationGuardRoute: educationGuardRouteWithChildren,
};

const educationRouteWithChildren = educationRoute._addFileChildren(educationRouteChildren);

interface AdminGuardRouteChildren {
  AdminGuardDashboardRoute: typeof AdminGuardDashboardRoute;
}

const AdminGuardRouteChildren: AdminGuardRouteChildren = {
  AdminGuardDashboardRoute: AdminGuardDashboardRoute,
};

const AdminGuardRouteWithChildren = AdminGuardRoute._addFileChildren(AdminGuardRouteChildren);

interface AdminRouteChildren {
  AdminGuardRoute: typeof AdminGuardRouteWithChildren;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGuardRoute: AdminGuardRouteWithChildren,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

interface AuthGuardRouteChildren {
  AuthGuardRecoverPasswordRoute: typeof AuthGuardRecoverPasswordRoute;
  AuthGuardSignInRoute: typeof AuthGuardSignInRoute;
  AuthGuardSignUpRoute: typeof AuthGuardSignUpRoute;
}

const AuthGuardRouteChildren: AuthGuardRouteChildren = {
  AuthGuardRecoverPasswordRoute: AuthGuardRecoverPasswordRoute,
  AuthGuardSignInRoute: AuthGuardSignInRoute,
  AuthGuardSignUpRoute: AuthGuardSignUpRoute,
};

const AuthGuardRouteWithChildren = AuthGuardRoute._addFileChildren(AuthGuardRouteChildren);

interface AuthRouteChildren {
  AuthGuardRoute: typeof AuthGuardRouteWithChildren;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGuardRoute: AuthGuardRouteWithChildren,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof educationGuardIndexRoute;
  '/admin': typeof AdminGuardRouteWithChildren;
  '/auth': typeof AuthGuardRouteWithChildren;
  '/test': typeof educationGuardTestRoute;
  '/admin/dashboard': typeof AdminGuardDashboardRoute;
  '/auth/recover-password': typeof AuthGuardRecoverPasswordRoute;
  '/auth/sign-in': typeof AuthGuardSignInRoute;
  '/auth/sign-up': typeof AuthGuardSignUpRoute;
}

export interface FileRoutesByTo {
  '/admin': typeof AdminGuardRouteWithChildren;
  '/auth': typeof AuthGuardRouteWithChildren;
  '/test': typeof educationGuardTestRoute;
  '/admin/dashboard': typeof AdminGuardDashboardRoute;
  '/auth/recover-password': typeof AuthGuardRecoverPasswordRoute;
  '/auth/sign-in': typeof AuthGuardSignInRoute;
  '/auth/sign-up': typeof AuthGuardSignUpRoute;
  '/': typeof educationGuardIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/(education)': typeof educationRouteWithChildren;
  '/(education)/_guard': typeof educationGuardRouteWithChildren;
  '/admin': typeof AdminRouteWithChildren;
  '/admin/_guard': typeof AdminGuardRouteWithChildren;
  '/auth': typeof AuthRouteWithChildren;
  '/auth/_guard': typeof AuthGuardRouteWithChildren;
  '/(education)/_guard/test': typeof educationGuardTestRoute;
  '/admin/_guard/dashboard': typeof AdminGuardDashboardRoute;
  '/auth/_guard/recover-password': typeof AuthGuardRecoverPasswordRoute;
  '/auth/_guard/sign-in': typeof AuthGuardSignInRoute;
  '/auth/_guard/sign-up': typeof AuthGuardSignUpRoute;
  '/(education)/_guard/': typeof educationGuardIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/test'
    | '/admin/dashboard'
    | '/auth/recover-password'
    | '/auth/sign-in'
    | '/auth/sign-up';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/admin'
    | '/auth'
    | '/test'
    | '/admin/dashboard'
    | '/auth/recover-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/';
  id:
    | '__root__'
    | '/(education)'
    | '/(education)/_guard'
    | '/admin'
    | '/admin/_guard'
    | '/auth'
    | '/auth/_guard'
    | '/(education)/_guard/test'
    | '/admin/_guard/dashboard'
    | '/auth/_guard/recover-password'
    | '/auth/_guard/sign-in'
    | '/auth/_guard/sign-up'
    | '/(education)/_guard/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  educationRoute: typeof educationRouteWithChildren;
  AdminRoute: typeof AdminRouteWithChildren;
  AuthRoute: typeof AuthRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  educationRoute: educationRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(education)",
        "/admin",
        "/auth"
      ]
    },
    "/(education)": {
      "filePath": "(education)",
      "children": [
        "/(education)/_guard"
      ]
    },
    "/(education)/_guard": {
      "filePath": "(education)/_guard.tsx",
      "parent": "/(education)",
      "children": [
        "/(education)/_guard/test",
        "/(education)/_guard/"
      ]
    },
    "/admin": {
      "filePath": "admin",
      "children": [
        "/admin/_guard"
      ]
    },
    "/admin/_guard": {
      "filePath": "admin/_guard.tsx",
      "parent": "/admin",
      "children": [
        "/admin/_guard/dashboard"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_guard"
      ]
    },
    "/auth/_guard": {
      "filePath": "auth/_guard.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_guard/recover-password",
        "/auth/_guard/sign-in",
        "/auth/_guard/sign-up"
      ]
    },
    "/(education)/_guard/test": {
      "filePath": "(education)/_guard/test.tsx",
      "parent": "/(education)/_guard"
    },
    "/admin/_guard/dashboard": {
      "filePath": "admin/_guard/dashboard.tsx",
      "parent": "/admin/_guard"
    },
    "/auth/_guard/recover-password": {
      "filePath": "auth/_guard/recover-password.tsx",
      "parent": "/auth/_guard"
    },
    "/auth/_guard/sign-in": {
      "filePath": "auth/_guard/sign-in.tsx",
      "parent": "/auth/_guard"
    },
    "/auth/_guard/sign-up": {
      "filePath": "auth/_guard/sign-up.tsx",
      "parent": "/auth/_guard"
    },
    "/(education)/_guard/": {
      "filePath": "(education)/_guard/index.tsx",
      "parent": "/(education)/_guard"
    }
  }
}
ROUTE_MANIFEST_END */
