/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as AuthGuardImport } from './routes/auth/_guard';
import { Route as AdminGuardImport } from './routes/admin/_guard';
import { Route as educationGuardImport } from './routes/(education)/_guard';
import { Route as educationGuardIndexImport } from './routes/(education)/_guard/index';
import { Route as AuthGuardSignUpImport } from './routes/auth/_guard/sign-up';
import { Route as AuthGuardSignInImport } from './routes/auth/_guard/sign-in';
import { Route as AuthGuardRecoverPasswordImport } from './routes/auth/_guard/recover-password';
import { Route as AdminGuardUsersImport } from './routes/admin/_guard/users';
import { Route as AdminGuardTransactionsImport } from './routes/admin/_guard/transactions';
import { Route as educationGuardTransactionsImport } from './routes/(education)/_guard/transactions';
import { Route as educationGuardShopImport } from './routes/(education)/_guard/shop';
import { Route as educationGuardProfileImport } from './routes/(education)/_guard/profile';
import { Route as AdminGuardCoursesIndexImport } from './routes/admin/_guard/courses_/index';
import { Route as AdminGuardCoursesCourseImport } from './routes/admin/_guard/courses_/$course';
import { Route as educationGuardCoursesCourseImport } from './routes/(education)/_guard/courses_/$course';
import { Route as AdminGuardCoursesCourseModulesModuleImport } from './routes/admin/_guard/courses_/$course_.modules_.$module';
import { Route as educationGuardCoursesCourseLessonsLessonImport } from './routes/(education)/_guard/courses_/$course_.lessons_.$lesson';
import { Route as AdminGuardCoursesCourseModulesModuleLessonsLessonImport } from './routes/admin/_guard/courses_/$course_.modules_.$module_.lessons_.$lesson';

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')();
const AdminImport = createFileRoute('/admin')();
const educationImport = createFileRoute('/(education)')();

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any);

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any);

const educationRoute = educationImport.update({
  id: '/(education)',
  getParentRoute: () => rootRoute,
} as any);

const AuthGuardRoute = AuthGuardImport.update({
  id: '/_guard',
  getParentRoute: () => AuthRoute,
} as any);

const AdminGuardRoute = AdminGuardImport.update({
  id: '/_guard',
  getParentRoute: () => AdminRoute,
} as any);

const educationGuardRoute = educationGuardImport.update({
  id: '/_guard',
  getParentRoute: () => educationRoute,
} as any);

const educationGuardIndexRoute = educationGuardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => educationGuardRoute,
} as any);

const AuthGuardSignUpRoute = AuthGuardSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthGuardRoute,
} as any);

const AuthGuardSignInRoute = AuthGuardSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthGuardRoute,
} as any);

const AuthGuardRecoverPasswordRoute = AuthGuardRecoverPasswordImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => AuthGuardRoute,
} as any);

const AdminGuardUsersRoute = AdminGuardUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminGuardRoute,
} as any);

const AdminGuardTransactionsRoute = AdminGuardTransactionsImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminGuardRoute,
} as any);

const educationGuardTransactionsRoute = educationGuardTransactionsImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => educationGuardRoute,
} as any);

const educationGuardShopRoute = educationGuardShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => educationGuardRoute,
} as any);

const educationGuardProfileRoute = educationGuardProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => educationGuardRoute,
} as any);

const AdminGuardCoursesIndexRoute = AdminGuardCoursesIndexImport.update({
  id: '/courses_/',
  path: '/courses/',
  getParentRoute: () => AdminGuardRoute,
} as any);

const AdminGuardCoursesCourseRoute = AdminGuardCoursesCourseImport.update({
  id: '/courses_/$course',
  path: '/courses/$course',
  getParentRoute: () => AdminGuardRoute,
} as any);

const educationGuardCoursesCourseRoute = educationGuardCoursesCourseImport.update({
  id: '/courses_/$course',
  path: '/courses/$course',
  getParentRoute: () => educationGuardRoute,
} as any);

const AdminGuardCoursesCourseModulesModuleRoute = AdminGuardCoursesCourseModulesModuleImport.update({
  id: '/courses_/$course_/modules_/$module',
  path: '/courses/$course/modules/$module',
  getParentRoute: () => AdminGuardRoute,
} as any);

const educationGuardCoursesCourseLessonsLessonRoute = educationGuardCoursesCourseLessonsLessonImport.update({
  id: '/courses_/$course_/lessons_/$lesson',
  path: '/courses/$course/lessons/$lesson',
  getParentRoute: () => educationGuardRoute,
} as any);

const AdminGuardCoursesCourseModulesModuleLessonsLessonRoute =
  AdminGuardCoursesCourseModulesModuleLessonsLessonImport.update({
    id: '/courses_/$course_/modules_/$module_/lessons_/$lesson',
    path: '/courses/$course/modules/$module/lessons/$lesson',
    getParentRoute: () => AdminGuardRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(education)': {
      id: '/(education)';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof educationImport;
      parentRoute: typeof rootRoute;
    };
    '/(education)/_guard': {
      id: '/(education)/_guard';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof educationGuardImport;
      parentRoute: typeof educationRoute;
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminImport;
      parentRoute: typeof rootRoute;
    };
    '/admin/_guard': {
      id: '/admin/_guard';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminGuardImport;
      parentRoute: typeof AdminRoute;
    };
    '/auth': {
      id: '/auth';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    '/auth/_guard': {
      id: '/auth/_guard';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof AuthGuardImport;
      parentRoute: typeof AuthRoute;
    };
    '/(education)/_guard/profile': {
      id: '/(education)/_guard/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof educationGuardProfileImport;
      parentRoute: typeof educationGuardImport;
    };
    '/(education)/_guard/shop': {
      id: '/(education)/_guard/shop';
      path: '/shop';
      fullPath: '/shop';
      preLoaderRoute: typeof educationGuardShopImport;
      parentRoute: typeof educationGuardImport;
    };
    '/(education)/_guard/transactions': {
      id: '/(education)/_guard/transactions';
      path: '/transactions';
      fullPath: '/transactions';
      preLoaderRoute: typeof educationGuardTransactionsImport;
      parentRoute: typeof educationGuardImport;
    };
    '/admin/_guard/transactions': {
      id: '/admin/_guard/transactions';
      path: '/transactions';
      fullPath: '/admin/transactions';
      preLoaderRoute: typeof AdminGuardTransactionsImport;
      parentRoute: typeof AdminGuardImport;
    };
    '/admin/_guard/users': {
      id: '/admin/_guard/users';
      path: '/users';
      fullPath: '/admin/users';
      preLoaderRoute: typeof AdminGuardUsersImport;
      parentRoute: typeof AdminGuardImport;
    };
    '/auth/_guard/recover-password': {
      id: '/auth/_guard/recover-password';
      path: '/recover-password';
      fullPath: '/auth/recover-password';
      preLoaderRoute: typeof AuthGuardRecoverPasswordImport;
      parentRoute: typeof AuthGuardImport;
    };
    '/auth/_guard/sign-in': {
      id: '/auth/_guard/sign-in';
      path: '/sign-in';
      fullPath: '/auth/sign-in';
      preLoaderRoute: typeof AuthGuardSignInImport;
      parentRoute: typeof AuthGuardImport;
    };
    '/auth/_guard/sign-up': {
      id: '/auth/_guard/sign-up';
      path: '/sign-up';
      fullPath: '/auth/sign-up';
      preLoaderRoute: typeof AuthGuardSignUpImport;
      parentRoute: typeof AuthGuardImport;
    };
    '/(education)/_guard/': {
      id: '/(education)/_guard/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof educationGuardIndexImport;
      parentRoute: typeof educationGuardImport;
    };
    '/(education)/_guard/courses_/$course': {
      id: '/(education)/_guard/courses_/$course';
      path: '/courses/$course';
      fullPath: '/courses/$course';
      preLoaderRoute: typeof educationGuardCoursesCourseImport;
      parentRoute: typeof educationGuardImport;
    };
    '/admin/_guard/courses_/$course': {
      id: '/admin/_guard/courses_/$course';
      path: '/courses/$course';
      fullPath: '/admin/courses/$course';
      preLoaderRoute: typeof AdminGuardCoursesCourseImport;
      parentRoute: typeof AdminGuardImport;
    };
    '/admin/_guard/courses_/': {
      id: '/admin/_guard/courses_/';
      path: '/courses';
      fullPath: '/admin/courses';
      preLoaderRoute: typeof AdminGuardCoursesIndexImport;
      parentRoute: typeof AdminGuardImport;
    };
    '/(education)/_guard/courses_/$course_/lessons_/$lesson': {
      id: '/(education)/_guard/courses_/$course_/lessons_/$lesson';
      path: '/courses/$course/lessons/$lesson';
      fullPath: '/courses/$course/lessons/$lesson';
      preLoaderRoute: typeof educationGuardCoursesCourseLessonsLessonImport;
      parentRoute: typeof educationGuardImport;
    };
    '/admin/_guard/courses_/$course_/modules_/$module': {
      id: '/admin/_guard/courses_/$course_/modules_/$module';
      path: '/courses/$course/modules/$module';
      fullPath: '/admin/courses/$course/modules/$module';
      preLoaderRoute: typeof AdminGuardCoursesCourseModulesModuleImport;
      parentRoute: typeof AdminGuardImport;
    };
    '/admin/_guard/courses_/$course_/modules_/$module_/lessons_/$lesson': {
      id: '/admin/_guard/courses_/$course_/modules_/$module_/lessons_/$lesson';
      path: '/courses/$course/modules/$module/lessons/$lesson';
      fullPath: '/admin/courses/$course/modules/$module/lessons/$lesson';
      preLoaderRoute: typeof AdminGuardCoursesCourseModulesModuleLessonsLessonImport;
      parentRoute: typeof AdminGuardImport;
    };
  }
}

// Create and export the route tree

interface educationGuardRouteChildren {
  educationGuardProfileRoute: typeof educationGuardProfileRoute;
  educationGuardShopRoute: typeof educationGuardShopRoute;
  educationGuardTransactionsRoute: typeof educationGuardTransactionsRoute;
  educationGuardIndexRoute: typeof educationGuardIndexRoute;
  educationGuardCoursesCourseRoute: typeof educationGuardCoursesCourseRoute;
  educationGuardCoursesCourseLessonsLessonRoute: typeof educationGuardCoursesCourseLessonsLessonRoute;
}

const educationGuardRouteChildren: educationGuardRouteChildren = {
  educationGuardProfileRoute: educationGuardProfileRoute,
  educationGuardShopRoute: educationGuardShopRoute,
  educationGuardTransactionsRoute: educationGuardTransactionsRoute,
  educationGuardIndexRoute: educationGuardIndexRoute,
  educationGuardCoursesCourseRoute: educationGuardCoursesCourseRoute,
  educationGuardCoursesCourseLessonsLessonRoute: educationGuardCoursesCourseLessonsLessonRoute,
};

const educationGuardRouteWithChildren = educationGuardRoute._addFileChildren(educationGuardRouteChildren);

interface educationRouteChildren {
  educationGuardRoute: typeof educationGuardRouteWithChildren;
}

const educationRouteChildren: educationRouteChildren = {
  educationGuardRoute: educationGuardRouteWithChildren,
};

const educationRouteWithChildren = educationRoute._addFileChildren(educationRouteChildren);

interface AdminGuardRouteChildren {
  AdminGuardTransactionsRoute: typeof AdminGuardTransactionsRoute;
  AdminGuardUsersRoute: typeof AdminGuardUsersRoute;
  AdminGuardCoursesCourseRoute: typeof AdminGuardCoursesCourseRoute;
  AdminGuardCoursesIndexRoute: typeof AdminGuardCoursesIndexRoute;
  AdminGuardCoursesCourseModulesModuleRoute: typeof AdminGuardCoursesCourseModulesModuleRoute;
  AdminGuardCoursesCourseModulesModuleLessonsLessonRoute: typeof AdminGuardCoursesCourseModulesModuleLessonsLessonRoute;
}

const AdminGuardRouteChildren: AdminGuardRouteChildren = {
  AdminGuardTransactionsRoute: AdminGuardTransactionsRoute,
  AdminGuardUsersRoute: AdminGuardUsersRoute,
  AdminGuardCoursesCourseRoute: AdminGuardCoursesCourseRoute,
  AdminGuardCoursesIndexRoute: AdminGuardCoursesIndexRoute,
  AdminGuardCoursesCourseModulesModuleRoute: AdminGuardCoursesCourseModulesModuleRoute,
  AdminGuardCoursesCourseModulesModuleLessonsLessonRoute: AdminGuardCoursesCourseModulesModuleLessonsLessonRoute,
};

const AdminGuardRouteWithChildren = AdminGuardRoute._addFileChildren(AdminGuardRouteChildren);

interface AdminRouteChildren {
  AdminGuardRoute: typeof AdminGuardRouteWithChildren;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGuardRoute: AdminGuardRouteWithChildren,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

interface AuthGuardRouteChildren {
  AuthGuardRecoverPasswordRoute: typeof AuthGuardRecoverPasswordRoute;
  AuthGuardSignInRoute: typeof AuthGuardSignInRoute;
  AuthGuardSignUpRoute: typeof AuthGuardSignUpRoute;
}

const AuthGuardRouteChildren: AuthGuardRouteChildren = {
  AuthGuardRecoverPasswordRoute: AuthGuardRecoverPasswordRoute,
  AuthGuardSignInRoute: AuthGuardSignInRoute,
  AuthGuardSignUpRoute: AuthGuardSignUpRoute,
};

const AuthGuardRouteWithChildren = AuthGuardRoute._addFileChildren(AuthGuardRouteChildren);

interface AuthRouteChildren {
  AuthGuardRoute: typeof AuthGuardRouteWithChildren;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGuardRoute: AuthGuardRouteWithChildren,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof educationGuardIndexRoute;
  '/admin': typeof AdminGuardRouteWithChildren;
  '/auth': typeof AuthGuardRouteWithChildren;
  '/profile': typeof educationGuardProfileRoute;
  '/shop': typeof educationGuardShopRoute;
  '/transactions': typeof educationGuardTransactionsRoute;
  '/admin/transactions': typeof AdminGuardTransactionsRoute;
  '/admin/users': typeof AdminGuardUsersRoute;
  '/auth/recover-password': typeof AuthGuardRecoverPasswordRoute;
  '/auth/sign-in': typeof AuthGuardSignInRoute;
  '/auth/sign-up': typeof AuthGuardSignUpRoute;
  '/courses/$course': typeof educationGuardCoursesCourseRoute;
  '/admin/courses/$course': typeof AdminGuardCoursesCourseRoute;
  '/admin/courses': typeof AdminGuardCoursesIndexRoute;
  '/courses/$course/lessons/$lesson': typeof educationGuardCoursesCourseLessonsLessonRoute;
  '/admin/courses/$course/modules/$module': typeof AdminGuardCoursesCourseModulesModuleRoute;
  '/admin/courses/$course/modules/$module/lessons/$lesson': typeof AdminGuardCoursesCourseModulesModuleLessonsLessonRoute;
}

export interface FileRoutesByTo {
  '/admin': typeof AdminGuardRouteWithChildren;
  '/auth': typeof AuthGuardRouteWithChildren;
  '/profile': typeof educationGuardProfileRoute;
  '/shop': typeof educationGuardShopRoute;
  '/transactions': typeof educationGuardTransactionsRoute;
  '/admin/transactions': typeof AdminGuardTransactionsRoute;
  '/admin/users': typeof AdminGuardUsersRoute;
  '/auth/recover-password': typeof AuthGuardRecoverPasswordRoute;
  '/auth/sign-in': typeof AuthGuardSignInRoute;
  '/auth/sign-up': typeof AuthGuardSignUpRoute;
  '/': typeof educationGuardIndexRoute;
  '/courses/$course': typeof educationGuardCoursesCourseRoute;
  '/admin/courses/$course': typeof AdminGuardCoursesCourseRoute;
  '/admin/courses': typeof AdminGuardCoursesIndexRoute;
  '/courses/$course/lessons/$lesson': typeof educationGuardCoursesCourseLessonsLessonRoute;
  '/admin/courses/$course/modules/$module': typeof AdminGuardCoursesCourseModulesModuleRoute;
  '/admin/courses/$course/modules/$module/lessons/$lesson': typeof AdminGuardCoursesCourseModulesModuleLessonsLessonRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/(education)': typeof educationRouteWithChildren;
  '/(education)/_guard': typeof educationGuardRouteWithChildren;
  '/admin': typeof AdminRouteWithChildren;
  '/admin/_guard': typeof AdminGuardRouteWithChildren;
  '/auth': typeof AuthRouteWithChildren;
  '/auth/_guard': typeof AuthGuardRouteWithChildren;
  '/(education)/_guard/profile': typeof educationGuardProfileRoute;
  '/(education)/_guard/shop': typeof educationGuardShopRoute;
  '/(education)/_guard/transactions': typeof educationGuardTransactionsRoute;
  '/admin/_guard/transactions': typeof AdminGuardTransactionsRoute;
  '/admin/_guard/users': typeof AdminGuardUsersRoute;
  '/auth/_guard/recover-password': typeof AuthGuardRecoverPasswordRoute;
  '/auth/_guard/sign-in': typeof AuthGuardSignInRoute;
  '/auth/_guard/sign-up': typeof AuthGuardSignUpRoute;
  '/(education)/_guard/': typeof educationGuardIndexRoute;
  '/(education)/_guard/courses_/$course': typeof educationGuardCoursesCourseRoute;
  '/admin/_guard/courses_/$course': typeof AdminGuardCoursesCourseRoute;
  '/admin/_guard/courses_/': typeof AdminGuardCoursesIndexRoute;
  '/(education)/_guard/courses_/$course_/lessons_/$lesson': typeof educationGuardCoursesCourseLessonsLessonRoute;
  '/admin/_guard/courses_/$course_/modules_/$module': typeof AdminGuardCoursesCourseModulesModuleRoute;
  '/admin/_guard/courses_/$course_/modules_/$module_/lessons_/$lesson': typeof AdminGuardCoursesCourseModulesModuleLessonsLessonRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/profile'
    | '/shop'
    | '/transactions'
    | '/admin/transactions'
    | '/admin/users'
    | '/auth/recover-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/courses/$course'
    | '/admin/courses/$course'
    | '/admin/courses'
    | '/courses/$course/lessons/$lesson'
    | '/admin/courses/$course/modules/$module'
    | '/admin/courses/$course/modules/$module/lessons/$lesson';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/admin'
    | '/auth'
    | '/profile'
    | '/shop'
    | '/transactions'
    | '/admin/transactions'
    | '/admin/users'
    | '/auth/recover-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/courses/$course'
    | '/admin/courses/$course'
    | '/admin/courses'
    | '/courses/$course/lessons/$lesson'
    | '/admin/courses/$course/modules/$module'
    | '/admin/courses/$course/modules/$module/lessons/$lesson';
  id:
    | '__root__'
    | '/(education)'
    | '/(education)/_guard'
    | '/admin'
    | '/admin/_guard'
    | '/auth'
    | '/auth/_guard'
    | '/(education)/_guard/profile'
    | '/(education)/_guard/shop'
    | '/(education)/_guard/transactions'
    | '/admin/_guard/transactions'
    | '/admin/_guard/users'
    | '/auth/_guard/recover-password'
    | '/auth/_guard/sign-in'
    | '/auth/_guard/sign-up'
    | '/(education)/_guard/'
    | '/(education)/_guard/courses_/$course'
    | '/admin/_guard/courses_/$course'
    | '/admin/_guard/courses_/'
    | '/(education)/_guard/courses_/$course_/lessons_/$lesson'
    | '/admin/_guard/courses_/$course_/modules_/$module'
    | '/admin/_guard/courses_/$course_/modules_/$module_/lessons_/$lesson';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  educationRoute: typeof educationRouteWithChildren;
  AdminRoute: typeof AdminRouteWithChildren;
  AuthRoute: typeof AuthRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  educationRoute: educationRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(education)",
        "/admin",
        "/auth"
      ]
    },
    "/(education)": {
      "filePath": "(education)",
      "children": [
        "/(education)/_guard"
      ]
    },
    "/(education)/_guard": {
      "filePath": "(education)/_guard.tsx",
      "parent": "/(education)",
      "children": [
        "/(education)/_guard/profile",
        "/(education)/_guard/shop",
        "/(education)/_guard/transactions",
        "/(education)/_guard/",
        "/(education)/_guard/courses_/$course",
        "/(education)/_guard/courses_/$course_/lessons_/$lesson"
      ]
    },
    "/admin": {
      "filePath": "admin",
      "children": [
        "/admin/_guard"
      ]
    },
    "/admin/_guard": {
      "filePath": "admin/_guard.tsx",
      "parent": "/admin",
      "children": [
        "/admin/_guard/transactions",
        "/admin/_guard/users",
        "/admin/_guard/courses_/$course",
        "/admin/_guard/courses_/",
        "/admin/_guard/courses_/$course_/modules_/$module",
        "/admin/_guard/courses_/$course_/modules_/$module_/lessons_/$lesson"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_guard"
      ]
    },
    "/auth/_guard": {
      "filePath": "auth/_guard.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_guard/recover-password",
        "/auth/_guard/sign-in",
        "/auth/_guard/sign-up"
      ]
    },
    "/(education)/_guard/profile": {
      "filePath": "(education)/_guard/profile.tsx",
      "parent": "/(education)/_guard"
    },
    "/(education)/_guard/shop": {
      "filePath": "(education)/_guard/shop.tsx",
      "parent": "/(education)/_guard"
    },
    "/(education)/_guard/transactions": {
      "filePath": "(education)/_guard/transactions.tsx",
      "parent": "/(education)/_guard"
    },
    "/admin/_guard/transactions": {
      "filePath": "admin/_guard/transactions.tsx",
      "parent": "/admin/_guard"
    },
    "/admin/_guard/users": {
      "filePath": "admin/_guard/users.tsx",
      "parent": "/admin/_guard"
    },
    "/auth/_guard/recover-password": {
      "filePath": "auth/_guard/recover-password.tsx",
      "parent": "/auth/_guard"
    },
    "/auth/_guard/sign-in": {
      "filePath": "auth/_guard/sign-in.tsx",
      "parent": "/auth/_guard"
    },
    "/auth/_guard/sign-up": {
      "filePath": "auth/_guard/sign-up.tsx",
      "parent": "/auth/_guard"
    },
    "/(education)/_guard/": {
      "filePath": "(education)/_guard/index.tsx",
      "parent": "/(education)/_guard"
    },
    "/(education)/_guard/courses_/$course": {
      "filePath": "(education)/_guard/courses_/$course.tsx",
      "parent": "/(education)/_guard"
    },
    "/admin/_guard/courses_/$course": {
      "filePath": "admin/_guard/courses_/$course.tsx",
      "parent": "/admin/_guard"
    },
    "/admin/_guard/courses_/": {
      "filePath": "admin/_guard/courses_/index.tsx",
      "parent": "/admin/_guard"
    },
    "/(education)/_guard/courses_/$course_/lessons_/$lesson": {
      "filePath": "(education)/_guard/courses_/$course_.lessons_.$lesson.tsx",
      "parent": "/(education)/_guard"
    },
    "/admin/_guard/courses_/$course_/modules_/$module": {
      "filePath": "admin/_guard/courses_/$course_.modules_.$module.tsx",
      "parent": "/admin/_guard"
    },
    "/admin/_guard/courses_/$course_/modules_/$module_/lessons_/$lesson": {
      "filePath": "admin/_guard/courses_/$course_.modules_.$module_.lessons_.$lesson.tsx",
      "parent": "/admin/_guard"
    }
  }
}
ROUTE_MANIFEST_END */
